---
- name: Install basic system tools
  hosts: all
  become: true
  tasks:
    - name: Install packages on Debian/Ubuntu
      apt:
        name:
          - htop
          - curl
          - git
          - unzip
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install packages on RHEL/CentOS
      yum:
        name:
          - htop
          - curl
          - git
          - unzip
        state: present
      when: ansible_os_family == "RedHat"
