
---
- name: Check disk usage and send warning if threshold exceeded
  hosts: all
  become: true
  gather_facts: false

  vars:
    disk_path: "/"
    disk_threshold: 80

  tasks:
    - name: Get disk usage percentage
      shell: df -h / | awk 'NR==2 {print $5}' | tr -d '%'
      register: disk_usage_raw

    - name: Set disk usage fact
      set_fact:
        disk_usage: "{{ disk_usage_raw.stdout | int }}"

    - name: Warn if disk usage exceeds threshold
      debug:
        msg: "⚠️ Disk usage is {{ disk_usage }}%, which exceeds threshold of {{ disk_threshold }}%"
      when: disk_usage | int > disk_threshold
