---
- name: Update NetBird package on Debian/Ubuntu and Alpine
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Update APT cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Upgrade NetBird (Debian/Ubuntu)
      apt:
        name: netbird
        state: latest
      when: ansible_os_family == "Debian"

    - name: Update APK cache (Alpine)
      apk:
        update_cache: yes
      when: ansible_distribution == "Alpine"

    - name: Upgrade NetBird (Alpine)
      apk:
        name: netbird
        state: latest
      when: ansible_distribution == "Alpine"

    - name: Restart NetBird service
      systemd:
        name: netbird
        state: restarted
        enabled: yes
      when: ansible_service_mgr == "systemd"

    - name: Show installed NetBird version
      command: netbird version
      register: netbird_version
      changed_when: false

    - name: Display NetBird version
      debug:
        msg: "Host {{ inventory_hostname }} has NetBird version: {{ netbird_version.stdout }}"
