---
- name: Cleanup unused Docker stuff
  hosts: all
  become: true
  tasks:

    - name: Prune unused Docker networks
      ansible.builtin.command: docker network prune -f
      register: network_prune
      changed_when: "'Total reclaimed space' in network_prune.stdout"

    - name: Show network prune result
      debug:
        var: network_prune.stdout

    - name: Prune unused Docker volumes
      ansible.builtin.command: docker volume prune -f
      register: volume_prune
      changed_when: "'Total reclaimed space' in volume_prune.stdout"

    - name: Show volume prune result
      debug:
        var: volume_prune.stdout
