---
- name: Update Debian/Ubuntu and Alpine servers
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Update APT cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages (Debian/Ubuntu)
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update all packages (Alpine Linux)
      apk:
        update_cache: yes
        upgrade: yes
      when: ansible_distribution == "Alpine"

    - name: Check if reboot is required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family == "Debian"

    - name: Notify if reboot is required (Debian/Ubuntu)
      debug:
        msg: "Host {{ inventory_hostname }} requires a reboot!"
      when:
        - ansible_os_family == "Debian"
        - reboot_required_file.stat.exists

    - name: Notify after upgrade (Alpine Linux)
      debug:
        msg: "Host {{ inventory_hostname }} has been upgraded (Alpine Linux). Reboot may be necessary manually if critical libraries were updated."
      when: ansible_distribution == "Alpine"
