---
- name: Update all servers
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Update APT cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages (Debian/Ubuntu)
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update YUM packages (RHEL/CentOS)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Check if reboot is required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family == "Debian"

    - name: Check if reboot is required (RHEL/CentOS)
      shell: needs-restarting -r; echo $?
      register: reboot_required_shell
      failed_when: false
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Notify if reboot is required (Debian/Ubuntu)
      debug:
        msg: "Host {{ inventory_hostname }} requires a reboot!"
      when:
        - ansible_os_family == "Debian"
        - reboot_required_file.stat.exists

    - name: Notify if reboot is required (RHEL/CentOS)
      debug:
        msg: "Host {{ inventory_hostname }} requires a reboot!"
      when:
        - ansible_os_family == "RedHat"
        - reboot_required_shell.stdout | int == 1
